##
## Makefile for  in /home/daguen_s/rendu/T2Rush1
##
## Made by daguen_s
## Login   <daguen_s@epitech.net>
##
## Started on  Sun Mar  9 19:19:18 2014 daguen_s
## Last update Sun Mar  9 19:27:43 2014 daguen_s
##

all:
	make -C etape_1
	make -C etape_2

clean:
	make clean -C etape_1
	make clean -C etape_2

fclean:
	make fclean -C etape_1
	make fclean -C etape_2

re:
	make re -C etape_1
	make re -C etape_2

.phony: all clean fclean re
